
// Dummy data for development and preview purposes
export const JOBS = [
  {
    id: "1",
    title: "Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    salary: "$120,000 - $150,000",
    description: "We are looking for a Software Engineer to join our team...",
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      "3+ years of experience in software development",
      "Proficiency in JavaScript, TypeScript, and React",
      "Experience with backend technologies like Node.js",
      "Knowledge of cloud platforms (AWS, GCP)",
    ],
    responsibilities: [
      "Develop and maintain web applications",
      "Collaborate with cross-functional teams",
      "Write clean, efficient, and maintainable code",
      "Participate in code reviews and provide feedback",
      "Troubleshoot and debug issues",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Flexible work schedule",
      "Remote work options",
    ],
    jobType: "Full-time",
    category: "IT Jobs",
    experience: "3-5 years",
    lastDate: "2023-12-31",
    postedDate: "2023-11-15",
    isHot: true,
    isNew: true,
  },
  {
    id: "2",
    title: "Product Manager",
    company: "Amazon",
    location: "Seattle, WA",
    salary: "$130,000 - $160,000",
    description: "Amazon is seeking a Product Manager to lead product development...",
    requirements: [
      "Bachelor's degree in Business, Computer Science, or related field",
      "5+ years of experience in product management",
      "Strong analytical and problem-solving skills",
      "Excellent communication and leadership abilities",
      "Experience with agile methodologies",
    ],
    responsibilities: [
      "Define product vision, strategy, and roadmap",
      "Work with engineering teams to deliver features",
      "Gather and prioritize product requirements",
      "Analyze market trends and competition",
      "Define and track success metrics",
    ],
    benefits: [
      "Competitive compensation package",
      "Comprehensive health benefits",
      "401(k) with company match",
      "Paid time off and parental leave",
      "Employee discounts",
    ],
    jobType: "Full-time",
    category: "Private Jobs",
    experience: "5+ years",
    lastDate: "2023-12-15",
    postedDate: "2023-11-10",
    isHot: true,
    isNew: false,
  },
  {
    id: "3",
    title: "Data Scientist",
    company: "Microsoft",
    location: "Redmond, WA",
    salary: "$125,000 - $155,000",
    description: "Microsoft is looking for a Data Scientist to join our AI team...",
    requirements: [
      "Master's or PhD in Computer Science, Statistics, or related field",
      "3+ years of experience in data science",
      "Strong programming skills in Python, R, or similar",
      "Experience with machine learning frameworks",
      "Knowledge of statistical analysis",
    ],
    responsibilities: [
      "Develop and implement machine learning models",
      "Analyze large datasets to extract insights",
      "Collaborate with product teams to implement AI features",
      "Monitor and improve model performance",
      "Stay updated with latest research in ML/AI",
    ],
    benefits: [
      "Competitive salary",
      "Comprehensive health coverage",
      "Retirement plans with matching",
      "Professional development opportunities",
      "Work-life balance programs",
    ],
    jobType: "Full-time",
    category: "IT Jobs",
    experience: "3-5 years",
    lastDate: "2023-12-20",
    postedDate: "2023-11-05",
    isHot: false,
    isNew: true,
  },
  {
    id: "4",
    title: "UX Designer",
    company: "Apple",
    location: "Cupertino, CA",
    salary: "$110,000 - $140,000",
    description: "Apple is seeking a talented UX Designer to create exceptional user experiences...",
    requirements: [
      "Bachelor's degree in Design, HCI, or related field",
      "4+ years of experience in UX design",
      "Proficiency in design tools (Figma, Sketch, Adobe XD)",
      "Strong portfolio demonstrating design thinking",
      "Experience with user research and testing",
    ],
    responsibilities: [
      "Create user-centered designs for digital products",
      "Develop wireframes, prototypes, and user flows",
      "Collaborate with cross-functional teams",
      "Conduct user research and usability testing",
      "Iterate designs based on user feedback",
    ],
    benefits: [
      "Competitive compensation",
      "Health and wellness benefits",
      "Stock options",
      "Education reimbursement",
      "Employee discounts",
    ],
    jobType: "Full-time",
    category: "Private Jobs",
    experience: "3-5 years",
    lastDate: "2023-12-25",
    postedDate: "2023-11-08",
    isHot: false,
    isNew: false,
  },
  {
    id: "5",
    title: "IT Security Analyst",
    company: "Bank of America",
    location: "Charlotte, NC",
    salary: "$95,000 - $120,000",
    description: "Bank of America is looking for an IT Security Analyst to protect our systems...",
    requirements: [
      "Bachelor's degree in Computer Science, Cybersecurity, or related field",
      "3+ years of experience in IT security",
      "Knowledge of security frameworks (NIST, ISO)",
      "Experience with security tools and technologies",
      "Security certifications (CISSP, CEH, etc.) preferred",
    ],
    responsibilities: [
      "Monitor systems for security threats",
      "Investigate and respond to security incidents",
      "Implement security controls and measures",
      "Conduct security assessments and audits",
      "Provide security awareness training",
    ],
    benefits: [
      "Competitive salary",
      "Comprehensive benefits package",
      "Retirement savings plan",
      "Tuition reimbursement",
      "Flexible work arrangements",
    ],
    jobType: "Full-time",
    category: "Bank Jobs",
    experience: "3-5 years",
    lastDate: "2023-12-10",
    postedDate: "2023-11-01",
    isHot: true,
    isNew: false,
  },
  {
    id: "6",
    title: "Station Manager",
    company: "Indian Railways",
    location: "Delhi, India",
    salary: "₹60,000 - ₹80,000",
    description: "Indian Railways is seeking a Station Manager to oversee operations...",
    requirements: [
      "Bachelor's degree in any discipline",
      "5+ years of experience in railways or transportation",
      "Knowledge of railway operations and safety protocols",
      "Strong leadership and communication skills",
      "Experience in staff management",
    ],
    responsibilities: [
      "Oversee daily station operations",
      "Ensure safety and security protocols are followed",
      "Manage station staff and resources",
      "Handle customer service issues",
      "Coordinate with various railway departments",
    ],
    benefits: [
      "Government salary scale",
      "Healthcare benefits",
      "Pension scheme",
      "Housing allowance",
      "Travel concessions",
    ],
    jobType: "Full-time",
    category: "Railway Jobs",
    experience: "5+ years",
    lastDate: "2023-12-05",
    postedDate: "2023-10-25",
    isHot: false,
    isNew: false,
  },
  {
    id: "7",
    title: "Project Engineer",
    company: "NTPC",
    location: "Hyderabad, India",
    salary: "₹70,000 - ₹90,000",
    description: "NTPC is looking for a Project Engineer to manage power plant projects...",
    requirements: [
      "Bachelor's degree in Electrical/Mechanical Engineering",
      "4+ years of experience in power sector",
      "Knowledge of power plant operations",
      "Project management skills",
      "Familiarity with safety standards",
    ],
    responsibilities: [
      "Oversee project planning and execution",
      "Coordinate with contractors and vendors",
      "Monitor project progress and budget",
      "Ensure compliance with safety regulations",
      "Prepare technical reports and documentation",
    ],
    benefits: [
      "Competitive PSU salary",
      "Performance-related pay",
      "Medical benefits",
      "Housing accommodation",
      "Professional development opportunities",
    ],
    jobType: "Full-time",
    category: "PSU Jobs",
    experience: "3-5 years",
    lastDate: "2023-12-15",
    postedDate: "2023-11-01",
    isHot: false,
    isNew: true,
  },
  {
    id: "8",
    title: "Administrative Officer",
    company: "SBI",
    location: "Mumbai, India",
    salary: "₹50,000 - ₹65,000",
    description: "State Bank of India is hiring an Administrative Officer to support operations...",
    requirements: [
      "Bachelor's degree in any discipline",
      "2+ years of administrative experience",
      "Knowledge of banking operations preferred",
      "Strong organizational and communication skills",
      "Proficiency in MS Office",
    ],
    responsibilities: [
      "Handle administrative duties",
      "Coordinate with various departments",
      "Maintain records and documentation",
      "Assist in HR-related activities",
      "Support branch operations",
    ],
    benefits: [
      "Banking sector salary",
      "Health insurance",
      "Pension benefits",
      "Loan concessions",
      "Career growth opportunities",
    ],
    jobType: "Full-time",
    category: "Bank Jobs",
    experience: "1-3 years",
    lastDate: "2023-12-10",
    postedDate: "2023-11-05",
    isHot: false,
    isNew: false,
  },
  {
    id: "9",
    title: "Front Desk Executive",
    company: "Taj Hotels",
    location: "Bangalore, India",
    salary: "₹25,000 - ₹35,000",
    description: "Taj Hotels is hiring a Front Desk Executive to provide exceptional guest service...",
    requirements: [
      "Bachelor's degree in Hospitality or related field",
      "1+ years of experience in hotel industry",
      "Excellent communication and interpersonal skills",
      "Customer service orientation",
      "Knowledge of hotel management systems",
    ],
    responsibilities: [
      "Welcome and check-in guests",
      "Handle guest inquiries and requests",
      "Process payments and manage reservations",
      "Coordinate with housekeeping and other departments",
      "Ensure guest satisfaction",
    ],
    benefits: [
      "Competitive salary",
      "Meals on duty",
      "Accommodation (case basis)",
      "Healthcare benefits",
      "Career advancement opportunities",
    ],
    jobType: "Full-time",
    category: "Private Jobs",
    experience: "1-3 years",
    lastDate: "2023-12-20",
    postedDate: "2023-11-10",
    isHot: false,
    isNew: false,
  },
  {
    id: "10",
    title: "Technical Support Engineer",
    company: "Wipro",
    location: "Pune, India",
    salary: "₹30,000 - ₹45,000",
    description: "Wipro is seeking a Technical Support Engineer to assist clients with IT issues...",
    requirements: [
      "Bachelor's degree in IT, Computer Science, or related field",
      "2+ years of experience in technical support",
      "Knowledge of networking and operating systems",
      "Troubleshooting skills",
      "Good communication abilities",
    ],
    responsibilities: [
      "Provide technical support to clients",
      "Troubleshoot hardware and software issues",
      "Document support activities",
      "Escalate complex issues to appropriate teams",
      "Follow up on open tickets",
    ],
    benefits: [
      "Industry-standard salary",
      "Health insurance",
      "Retirement benefits",
      "Learning & development opportunities",
      "Flexible work options",
    ],
    jobType: "Full-time",
    category: "IT Jobs",
    experience: "1-3 years",
    lastDate: "2023-12-25",
    postedDate: "2023-11-15",
    isHot: false,
    isNew: true,
  },
  {
    id: "11",
    title: "Marketing Specialist",
    company: "Unilever",
    location: "Gurgaon, India",
    salary: "₹40,000 - ₹60,000",
    description: "Unilever is looking for a Marketing Specialist to support brand campaigns...",
    requirements: [
      "Bachelor's degree in Marketing or related field",
      "3+ years of experience in marketing",
      "Knowledge of digital marketing channels",
      "Creative thinking and analytical skills",
      "Experience with marketing tools and software",
    ],
    responsibilities: [
      "Develop and implement marketing campaigns",
      "Create content for various channels",
      "Analyze marketing metrics and results",
      "Collaborate with creative and sales teams",
      "Stay updated with market trends",
    ],
    benefits: [
      "Competitive salary package",
      "Performance bonuses",
      "Health and wellness benefits",
      "Product discounts",
      "Professional growth opportunities",
    ],
    jobType: "Full-time",
    category: "Private Jobs",
    experience: "3-5 years",
    lastDate: "2023-12-15",
    postedDate: "2023-11-05",
    isHot: true,
    isNew: false,
  },
  {
    id: "12",
    title: "Assistant Professor",
    company: "IIT Delhi",
    location: "Delhi, India",
    salary: "₹80,000 - ₹1,00,000",
    description: "IIT Delhi is hiring Assistant Professors for the Computer Science department...",
    requirements: [
      "PhD in Computer Science or related field",
      "Research experience and publications",
      "Teaching experience at university level",
      "Strong knowledge in specific CS domains",
      "Good communication and presentation skills",
    ],
    responsibilities: [
      "Teach undergraduate and graduate courses",
      "Conduct research in specialized areas",
      "Guide student projects and theses",
      "Participate in departmental activities",
      "Contribute to curriculum development",
    ],
    benefits: [
      "Academic salary as per UGC norms",
      "Research grants",
      "Conference allowances",
      "Housing facilities",
      "Academic freedom",
    ],
    jobType: "Full-time",
    category: "Government Jobs",
    experience: "3-5 years",
    lastDate: "2023-12-31",
    postedDate: "2023-11-01",
    isHot: false,
    isNew: false,
  },
];
